package ServerApp;


/**
* ServerApp/ChatServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* jeudi 22 mars 2018 09 h 04 CET
*/

abstract public class ChatServiceHelper
{
  private static String  _id = "IDL:ServerApp/ChatService:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerApp.ChatService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerApp.ChatService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerApp.ChatServiceHelper.id (), "ChatService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerApp.ChatService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ChatServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerApp.ChatService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerApp.ChatService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerApp.ChatService)
      return (ServerApp.ChatService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerApp._ChatServiceStub stub = new ServerApp._ChatServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerApp.ChatService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerApp.ChatService)
      return (ServerApp.ChatService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerApp._ChatServiceStub stub = new ServerApp._ChatServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
