package ServerApp;


/**
* ServerApp/ChatServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* jeudi 22 mars 2018 09 h 04 CET
*/

public interface ChatServiceOperations 
{
  boolean sendMessage (String chatId, String usernameSender, String message);
  String newChat (String username1, String username2, boolean isPublic, ServerApp.Listener listener);
  String disconnect (String username1, String chatId, ServerApp.Listener listener);
} // interface ChatServiceOperations
