package ServerApp;


/**
* ServerApp/ChatServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* jeudi 22 mars 2018 09 h 04 CET
*/

public abstract class ChatServicePOA extends org.omg.PortableServer.Servant
 implements ServerApp.ChatServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendMessage", new java.lang.Integer (0));
    _methods.put ("newChat", new java.lang.Integer (1));
    _methods.put ("disconnect", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerApp/ChatService/sendMessage
       {
         String chatId = in.read_string ();
         String usernameSender = in.read_string ();
         String message = in.read_string ();
         boolean $result = false;
         $result = this.sendMessage (chatId, usernameSender, message);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ServerApp/ChatService/newChat
       {
         String username1 = in.read_string ();
         String username2 = in.read_string ();
         boolean isPublic = in.read_boolean ();
         ServerApp.Listener listener = ServerApp.ListenerHelper.read (in);
         String $result = null;
         $result = this.newChat (username1, username2, isPublic, listener);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerApp/ChatService/disconnect
       {
         String username1 = in.read_string ();
         String chatId = in.read_string ();
         ServerApp.Listener listener = ServerApp.ListenerHelper.read (in);
         String $result = null;
         $result = this.disconnect (username1, chatId, listener);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerApp/ChatService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ChatService _this() 
  {
    return ChatServiceHelper.narrow(
    super._this_object());
  }

  public ChatService _this(org.omg.CORBA.ORB orb) 
  {
    return ChatServiceHelper.narrow(
    super._this_object(orb));
  }


} // class ChatServicePOA
