package ServerApp;


/**
* ServerApp/listenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* mardi 20 mars 2018 16 h 34 CET
*/

public interface listenerOperations 
{
  void onMessageReceived (String message);
} // interface listenerOperations
