package ServerApp;


/**
* ServerApp/ListenerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* jeudi 22 mars 2018 09 h 04 CET
*/

abstract public class ListenerHelper
{
  private static String  _id = "IDL:ServerApp/Listener:1.0";

  public static void insert (org.omg.CORBA.Any a, ServerApp.Listener that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServerApp.Listener extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServerApp.ListenerHelper.id (), "Listener");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServerApp.Listener read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ListenerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServerApp.Listener value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServerApp.Listener narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerApp.Listener)
      return (ServerApp.Listener)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerApp._ListenerStub stub = new ServerApp._ListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServerApp.Listener unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServerApp.Listener)
      return (ServerApp.Listener)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServerApp._ListenerStub stub = new ServerApp._ListenerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
