package ServerApp;

/**
* ServerApp/listenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* mardi 20 mars 2018 16 h 34 CET
*/

public final class listenerHolder implements org.omg.CORBA.portable.Streamable
{
  public ServerApp.listener value = null;

  public listenerHolder ()
  {
  }

  public listenerHolder (ServerApp.listener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServerApp.listenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServerApp.listenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServerApp.listenerHelper.type ();
  }

}
