package ServerApp;


/**
* ServerApp/listener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* mardi 20 mars 2018 16 h 34 CET
*/

public interface listener extends listenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface listener
