package ServerApp;


/**
* ServerApp/ListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* jeudi 22 mars 2018 09 h 04 CET
*/

public abstract class ListenerPOA extends org.omg.PortableServer.Servant
 implements ServerApp.ListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("onMessageReceived", new java.lang.Integer (0));
    _methods.put ("onUserDisconnected", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerApp/Listener/onMessageReceived
       {
         String message = in.read_string ();
         this.onMessageReceived (message);
         out = $rh.createReply();
         break;
       }

       case 1:  // ServerApp/Listener/onUserDisconnected
       {
         String message = in.read_string ();
         this.onUserDisconnected (message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerApp/Listener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Listener _this() 
  {
    return ListenerHelper.narrow(
    super._this_object());
  }

  public Listener _this(org.omg.CORBA.ORB orb) 
  {
    return ListenerHelper.narrow(
    super._this_object(orb));
  }


} // class ListenerPOA
