package ServerApp;


/**
* ServerApp/UserServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* jeudi 22 mars 2018 09 h 04 CET
*/

public abstract class UserServicePOA extends org.omg.PortableServer.Servant
 implements ServerApp.UserServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("authenticate", new java.lang.Integer (0));
    _methods.put ("register", new java.lang.Integer (1));
    _methods.put ("newContactRequest", new java.lang.Integer (2));
    _methods.put ("getContactsDisplay", new java.lang.Integer (3));
    _methods.put ("getLastContactRequests", new java.lang.Integer (4));
    _methods.put ("answerToContactRequest", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServerApp/UserService/authenticate
       {
         String username = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.authenticate (username, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ServerApp/UserService/register
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String name = in.read_string ();
         String firstname = in.read_string ();
         String $result = null;
         $result = this.register (username, password, name, firstname);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerApp/UserService/newContactRequest
       {
         String username1 = in.read_string ();
         String username2 = in.read_string ();
         this.newContactRequest (username1, username2);
         out = $rh.createReply();
         break;
       }

       case 3:  // ServerApp/UserService/getContactsDisplay
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getContactsDisplay (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerApp/UserService/getLastContactRequests
       {
         String username = in.read_string ();
         String $result = null;
         $result = this.getLastContactRequests (username);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ServerApp/UserService/answerToContactRequest
       {
         String username = in.read_string ();
         boolean answer = in.read_boolean ();
         this.answerToContactRequest (username, answer);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerApp/UserService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public UserService _this() 
  {
    return UserServiceHelper.narrow(
    super._this_object());
  }

  public UserService _this(org.omg.CORBA.ORB orb) 
  {
    return UserServiceHelper.narrow(
    super._this_object(orb));
  }


} // class UserServicePOA
